<?php
/**
 * Created by PhpStorm.
 * User: nakedleafdesign
 * Date: 2018/04/12
 * Time: 17:29
 */

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_5ab6a359eeab1',
    'title' => 'UnitBuildSystem',
    'fields' => array(
      array(
        'key' => 'field_5ab6a36831fdb',
        'label' => 'コンテンツ',
        'name' => 'unitbuildsystem',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '100',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          '5ab6a382e7466' => array(
            'key' => '5ab6a382e7466',
            'name' => 'ubs_heading',
            'label' => '見出し',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab6ae0f542bf',
                'label' => '見出し',
                'name' => 'ubs_heading_edit',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5ab6ae37542c0',
                    'label' => 'タイプ',
                    'name' => 'ubs_heading_edit_type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '30',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      1 => '見出し1',
                      2 => '見出し2',
                      3 => '見出し3',
                      4 => '見出し4',
                      5 => '見出し5',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5ab6ae71542c1',
                    'label' => '見出し本文',
                    'name' => 'ubs_heading_edit_content',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '70',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_5ab6e0a858a66',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_heading',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab6af1a5a794' => array(
            'key' => '5ab6af1a5a794',
            'name' => 'ubs_text',
            'label' => '本文',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab6af2c5a795',
                'label' => '本文',
                'name' => 'ubs_text_edit',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'visual',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
              ),
              array(
                'key' => 'field_5ab6b8b73b80f',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_text',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7ab8883449' => array(
            'key' => '5ab7ab8883449',
            'name' => 'ubs_img',
            'label' => '画像',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab8f46f56000',
                'label' => '画像レイアウト',
                'name' => 'ubs_img_layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'img-layout--left' => '左寄せ',
                  'img-layout--center' => '中央寄せ',
                  'img-layout--right' => '右寄せ',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab7ab928344a',
                'label' => '画像設定',
                'name' => 'ubs_img_edit',
                'type' => 'repeater',
                'instructions' => '最大3つまで登録可能',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 3,
                'layout' => 'block',
                'button_label' => '画像を追加',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5ab7abe18344c',
                    'label' => '画像',
                    'name' => 'ubs_img_edit_item',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                      array(
                        'key' => 'field_5ab7b01f1e20e',
                        'label' => '画像',
                        'name' => 'ubs_img_edit_item_img',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '100',
                          'class' => '',
                          'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                      ),
                      array(
                        'key' => 'field_5ab7b0331e20f',
                        'label' => '画像詳細設定',
                        'name' => 'ubs_img_settings_img',
                        'type' => 'clone',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'clone' => array(
                          0 => 'group_5ab7aeb587653',
                        ),
                        'display' => 'seamless',
                        'layout' => 'block',
                        'prefix_label' => 0,
                        'prefix_name' => 1,
                      ),
                    ),
                  ),
                ),
              ),
              array(
                'key' => 'field_5ab7ada1dfb3f',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_img',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab75d1bceb2d' => array(
            'key' => '5ab75d1bceb2d',
            'name' => 'ubs_list',
            'label' => 'リスト',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab75e90309a0',
                'label' => 'リストタイプ',
                'name' => 'ubs_list_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '01' => 'タイプ1',
                  '02' => 'タイプ2',
                  'num' => '番号付',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab75fa14e971',
                'label' => 'リスト本文',
                'name' => 'ubs_list_edit',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5ab75fbe4e972',
                    'label' => '本文',
                    'name' => 'ubs_list_edit_item',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 2,
                    'new_lines' => 'br',
                  ),
                ),
              ),
              array(
                'key' => 'field_5ab7601436e88',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_list',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7691c1dbe6' => array(
            'key' => '5ab7691c1dbe6',
            'name' => 'ubs_btn',
            'label' => 'ボタン',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab769491dbe7',
                'label' => 'ボタンレイアウト',
                'name' => 'ubs_btn_layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'left' => '左寄せ',
                  'center' => '中央寄せ',
                  'right' => '右寄せ',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab76ab71dbec',
                'label' => 'ボタンタイプ',
                'name' => 'ubs_btn_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '01' => 'タイプ1',
                  '02' => 'タイプ2',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab769a71dbe8',
                'label' => 'ボタン',
                'name' => 'ubs_btn_edit',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5ab769ca1dbe9',
                    'label' => 'ボタン詳細',
                    'name' => 'ubs_btn_edit_item',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                      array(
                        'key' => 'field_5ab769f91dbea',
                        'label' => 'ボタン種類',
                        'name' => 'ubs_btn_edit_item_style',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'choices' => array(
                          'default' => '通常',
                          'primary' => 'プライマリ',
                          'success' => 'サクセス',
                          'warning' => 'ワーニング',
                          'error' => 'エラー',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                      ),
                      array(
                        'key' => 'field_5ab76b53d0403',
                        'label' => 'リンク',
                        'name' => 'ubs_btn_edit_item_link',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '50',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                      ),
                      array(
                        'key' => 'field_5ab76a741dbeb',
                        'label' => 'ボタン本文',
                        'name' => 'ubs_btn_edit_item_content',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '100',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                      ),
                    ),
                  ),
                ),
              ),
              array(
                'key' => 'field_5ab76b26d0402',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_btn',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab76c46d7fd5' => array(
            'key' => '5ab76c46d7fd5',
            'name' => 'ubs_backquote',
            'label' => '引用',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab76c7ad7fd6',
                'label' => '本文',
                'name' => 'ubs_backquote_content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 5,
                'new_lines' => 'br',
              ),
              array(
                'key' => 'field_5ab76ca8d7fd7',
                'label' => '引用元名称',
                'name' => 'ubs_backquote_cite_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_5ab76cd5d7fd8',
                'label' => '引用元URL',
                'name' => 'ubs_backquote_cite_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab76cebd7fd9',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_backquote',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7767f26e63' => array(
            'key' => '5ab7767f26e63',
            'name' => 'ubs_floating',
            'label' => '回り込み',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7769d26e64',
                'label' => '回り込みタイプ',
                'name' => 'ubs_floating_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'left' => '画像左',
                  'right' => '画像右',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab776ca26e65',
                'label' => 'コンテンツ',
                'name' => 'ubs_floating_edit',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5ab776f026e66',
                    'label' => '画像',
                    'name' => 'ubs_floating_edit_img',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array(
                    'key' => 'field_5ab7b1a5f5014',
                    'label' => '画像詳細設定',
                    'name' => 'ubs_img_settings_floating',
                    'type' => 'clone',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'clone' => array(
                      0 => 'group_5ab7aeb587653',
                    ),
                    'display' => 'seamless',
                    'layout' => 'block',
                    'prefix_label' => 0,
                    'prefix_name' => 1,
                  ),
                  array(
                    'key' => 'field_5ab7771a26e67',
                    'label' => '本文',
                    'name' => 'ubs_floating_edit_text',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'delay' => 0,
                  ),
                ),
              ),
              array(
                'key' => 'field_5ab777a626e69',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_floating',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab79ea42f42b' => array(
            'key' => '5ab79ea42f42b',
            'name' => 'ubs_column',
            'label' => 'カラム',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ac1f47b6f85e',
                'label' => 'Coming soon ...',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '現在開発中（使用不可）
※ UnitBuildSystem ver 1.2 にてリリース予定',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7a629073c3' => array(
            'key' => '5ab7a629073c3',
            'name' => 'ubs_grid',
            'label' => 'グリッド',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7a635073c4',
                'label' => 'Coming soon ...',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '現在開発中（使用不可）
※ UnitBuildSystem ver 1.2 にてリリース予定',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7a6b9d104e' => array(
            'key' => '5ab7a6b9d104e',
            'name' => 'ubs_youtube',
            'label' => 'Youtube',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7a6b9d104f',
                'label' => 'Coming soon ...',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '87',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '現在開発中（使用不可）
※ UnitBuildSystem ver 1.1 にてリリース予定',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7a735d938b' => array(
            'key' => '5ab7a735d938b',
            'name' => 'googlemap',
            'label' => 'GoogleMap',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7a746d938d',
                'label' => 'Coming soon ...',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '現在開発中（使用不可）
※ UnitBuildSystem ver 1.3 にてリリース予定',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7a42ee53d5' => array(
            'key' => '5ab7a42ee53d5',
            'name' => 'ubs_hr',
            'label' => '区切り',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7a43ce53d6',
                'label' => '区切りタイプ',
                'name' => 'ubs_hr_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'hr--md' => '区切り中',
                  'hr--lg' => '区切り大',
                  'hr--sm' => '区切り小',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5ab7a4abb4513',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_hr',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7a766d938e' => array(
            'key' => '5ab7a766d938e',
            'name' => 'ubs_code',
            'label' => 'コード',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7a76fd938f',
                'label' => 'コード',
                'name' => 'ubs_code_edit',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'text',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
              ),
              array(
                'key' => 'field_5ac1f2fddb945',
                'label' => '詳細設定',
                'name' => 'ubs_unit_setting_code',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'group_5ab6a995be61c',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '5ab7a83b4821a' => array(
            'key' => '5ab7a83b4821a',
            'name' => 'ubs_other',
            'label' => 'その他',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_5ab7a8414821b',
                'label' => 'その他のユニット',
                'name' => 'ubs_other_menu',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layouts' => array(
                  '5ab7a848597be' => array(
                    'key' => '5ab7a848597be',
                    'name' => 'ubs_other_menu_faq',
                    'label' => 'よくある質問',
                    'display' => 'block',
                    'sub_fields' => array(
                      array(
                        'key' => 'field_5abf5bdb4b09e',
                        'label' => 'よくある質問',
                        'name' => 'ubs_other_menu_faq_item',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '100',
                          'class' => '',
                          'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                          array(
                            'key' => 'field_5abf5c0a4b09f',
                            'label' => 'カテゴリー',
                            'name' => 'ubs_other_menu_faq_item_category',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                              'width' => '',
                              'class' => '',
                              'id' => '',
                            ),
                            'choices' => array(
                              'unisex' => '共通',
                              'mens' => '男性',
                              'ladies' => '女性',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 1,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                          ),
                          array(
                            'key' => 'field_5abf5c954b0a1',
                            'label' => '質問タイトル',
                            'name' => 'ubs_other_menu_faq_item_question',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                              'width' => '100',
                              'class' => '',
                              'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 3,
                            'new_lines' => '',
                          ),
                          array(
                            'key' => 'field_5abf5cc04b0a2',
                            'label' => '質問回答',
                            'name' => 'ubs_other_menu_faq_item_answer',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                              'width' => '100',
                              'class' => '',
                              'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 0,
                          ),
                          array(
                            'key' => 'field_5abf5d284b0a4',
                            'label' => '詳細設定',
                            'name' => 'ubs_unit_setting_other_faq',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                              'width' => '',
                              'class' => '',
                              'id' => '',
                            ),
                            'clone' => array(
                              0 => 'group_5ab6a995be61c',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 1,
                          ),
                        ),
                      ),
                    ),
                    'min' => '',
                    'max' => '',
                  ),
                ),
                'button_label' => 'ユニットを追加',
                'min' => '',
                'max' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'button_label' => 'ユニットを追加',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
        ),
      ),
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5ab7aeb587653',
    'title' => 'UnitBuildSystemImgSettings',
    'fields' => array(
      array(
        'key' => 'field_5ab7aec1f1cbe',
        'label' => '画像詳細設定',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5ab7aedcf1cbf',
        'label' => '画像サイズ',
        'name' => 'fld_img_size',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'md' => 'サイズ中',
          'lg' => 'サイズ大',
          'sm' => 'サイズ小',
          'default' => 'そのまま',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5ab7af2df1cc0',
        'label' => '画像スタイル',
        'name' => 'fld_img_style',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'default' => '通常',
          'radius' => '角丸',
          'circle' => '丸',
          'border' => '枠線',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5ab9114b90a57',
        'label' => 'レスポンシブ設定',
        'name' => 'fld_img_responsive',
        'type' => 'select',
        'instructions' => 'どの端末からサイズを1列に可変させるか',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '100',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'default' => 'タブレット',
          'md' => 'スマートフォン',
          'sm' => '可変させない',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 1,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5ab8e3c61c31e',
        'label' => '画像リンク',
        'name' => 'fld_img_link',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5ab8e4730b641',
        'label' => 'リンクを別タブで開くか？',
        'name' => 'fld_img_target',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5ab90f5e88dcd',
        'label' => 'キャプションを表示させるか？',
        'name' => 'fld_img_caption',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5ab7b1ec14d1c',
        'label' => '画像詳細設定エンドポイント',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 0,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5ab6a995be61c',
    'title' => 'UnitBuildSystemUnitSettings',
    'fields' => array(
      array(
        'key' => 'field_5ab759c6796e4',
        'label' => '詳細設定',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5ab6d516c1307',
        'label' => 'ID',
        'name' => 'fld_id',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => 'ubs-common-setting',
          'id' => 'ubs-common-setting',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ab6d52dc130b',
        'label' => 'Class',
        'name' => 'fld_class',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ab6d54bc130c',
        'label' => '余白',
        'name' => 'fld_margin',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'mb--default' => '通常',
          'mb--lg' => '余白大',
          'mb--md' => '余白中',
          'mb--sm' => '余白小',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5ab7b22c823aa',
        'label' => '詳細設定エンドポイント',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 0,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5ac39cec251e8',
    'title' => '会員情報登録',
    'fields' => array(
      array(
        'key' => 'field_5ac39d3fdbab3',
        'label' => '会員情報登録',
        'name' => 'regiserMemberGroup',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5ac39d8d26eed',
            'label' => 'お名前',
            'name' => 'regiserMemberGroup_name',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '40',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ac39db326eee',
            'label' => '性別',
            'name' => 'regiserMemberGroup_sex',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '30',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'mens' => '男性',
              'ladies' => '女性',
              'other' => 'その他',
            ),
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ac39ddd26eef',
            'label' => '趣向',
            'name' => 'regiserMemberGroup_type',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '30',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              's' => 'S',
              'm' => 'M',
              'both' => 'SM',
            ),
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ac39e1826ef0',
            'label' => '年代',
            'name' => 'regiserMemberGroup_age',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              '秘密' => '秘密',
              20 => '20代',
              30 => '30代',
              40 => '40代',
              50 => '50代',
              60 => '60代',
              70 => '70代',
            ),
            'default_value' => array(
              0 => '特に無し',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ac39ea526ef1',
            'label' => '希望年齢',
            'name' => 'regiserMemberGroup_hope',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ac39eef26ef2',
            'label' => '身長',
            'name' => 'regiserMemberGroup_height',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => 'cm',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ac39f2226ef3',
            'label' => '体重',
            'name' => 'regiserMemberGroup_weight',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              '普通' => '普通',
              '細身' => '細身',
              'ややぽっちゃり' => '普通プラス（ややぽっちゃり）',
              'ぽっちゃり' => 'ぽっちゃり（太っている）',
            ),
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5ac39ffe26ef4',
            'label' => '都道府県',
            'name' => 'regiserMemberGroup_zip01',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ac3a01726ef5',
            'label' => '地方',
            'name' => 'regiserMemberGroup_zip02',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ac3a03a26ef6',
            'label' => 'プロフィール画像',
            'name' => 'regiserMemberGroup_img',
            'type' => 'image',
            'instructions' => 'プロフィール画像を設定できます。
登録画像がない場合はデフォルトの画像が適用されます。',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '100',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5ac3b514e4e5e',
            'label' => 'プロフィール文',
            'name' => 'regiserMemberGroup_profile',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '100',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'members_list',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

endif;